workflows:
    android-workflow-id:
        name: Android Sample Workflow
        # .......    
        # .......
        # .......
    artifacts:
        paths:
          - android/app/build/outputs/apk/release/app-release.apk
    ios-workflow-id:
        name: iOS Sample Workflow
        # ......
