workflows:
    android-workflow-id:
        name: Android Sample Workflow
        # .......    
        # .......
        # .......
    ios-workflow-id:
        name: iOS Sample Workflow
        # ......
artifacts:
    android_apk: android/app/build/outputs/apk/release/app-release.apk
